drm: bridge: it6161: add missing gpio consumer header
commit  da548c5a97b13669b75b4a3abd0d08d8c7cc804a from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Fix it6161.c:2810:24: error: implicit declaration of function
'devm_gpiod_get_optional'.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>