LF-13827-6 net: ppfe: update the usage of eventfd_signal
commit  a73c64fdb4b5ee03bef175c88445b17b18f12c04 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Cope with the API change since the commit
1808acc4fab2 ("eventfd: simplify eventfd_signal()")

Otherwise will meet the following build error:
drivers/staging/fsl_ppfe/pfe_cdev.c: In function ‘hif_us_isr’:
drivers/staging/fsl_ppfe/pfe_cdev.c:112:17: error: too many arguments to function ‘eventfd_signal’
  112 |                 eventfd_signal(trigger, 1);
      |                 ^~~~~~~~~~~~~~

Reviewed-by: Wei Fang <wei.fang@nxp.com>
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>