net: sdk_dpaa: fix build issue of __assign_str
commit  4832f9d40ad017ec942828c5b406469924ba0e06 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

API changed since the commit
2c92ca849fcc ("tracing/treewide: Remove second parameter of __assign_str()")

../drivers/net/ethernet/freescale/sdk_dpaa/./dpaa_eth_trace.h: In function ‘perf_trace_dpaa_eth_fd’:
../drivers/net/ethernet/freescale/sdk_dpaa/./dpaa_eth_trace.h:88:17: error: ‘__assign_str’ undeclared (first use in this function)
   88 |                 __assign_str(name, netdev->name);
      |                 ^~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>