Revert "firmware: imx: remove duplicate scmi_imx_misc_ctrl_get()"
commit  ab6dbba2b5a16c9678c5544a3e5178f1cb3517f3 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

This reverts commit 540c830212edc908361c39d40df21772a8bda308 which
caused the following build errors with imx_v7_defconfig:

arm-poky-linux-gnueabi-ld: sound/soc/fsl/fsl_mqs.o: in function `fsl_mqs_sm_write':
fsl_mqs.c:(.text+0x38): undefined reference to `scmi_imx_misc_ctrl_set'
arm-poky-linux-gnueabi-ld: sound/soc/fsl/fsl_mqs.o: in function `fsl_mqs_sm_read':
fsl_mqs.c:(.text+0x60): undefined reference to `scmi_imx_misc_ctrl_get'
make[3]: *** [../scripts/Makefile.vmlinux:34: vmlinux] Error 1

Squashed: a74f9bd952 LF-12051: firmware: imx: fix compile error

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>