MLK-21985-8 media: isi: fix build for next 20190607 upgrade
commit  ee7a0b767a89f77bb90d54a34b85fac31bb04cda from
https://github.com/nxp-imx/linux-imx lf-6.12.y

API change due to commit:
7e98b7b542a4 ("media: v4l2: Get rid of ->vidioc_enum_fmt_vid_{cap, out}_mplane")

../drivers/staging/media/imx/imx8-isi-cap.c:1211:2: error: unknown field ‘vidioc_enum_fmt_vid_cap_mplane’ specified in initializer
  .vidioc_enum_fmt_vid_cap_mplane = mxc_isi_cap_enum_fmt_mplane,

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>