drivers: i2c: remove default y from I2C_IMX_FLEXIO config
When building kernel with kts test layer, COMPILE_TEST is set as y.
This causes I2C_IMX_FLEXIO to be enabled because there is default y
option in this kernel config. But the depended MFD_IMX_FLEXIO
config is not enabled, and causes below building issue:
drivers/i2c/busses/i2c-flexio.c:290: undefined reference to `flexio_sw_reset'
Therefore, remove default y to avoid building issue. In this way, users
also can select proper driver based on specific SoC.

Signed-off-by: Meng Li <Meng.Li@windriver.com>