LF-6810-05: media: isi media: fix build error due to API renamed
commit  34373ccc5459c3d9bbbbfad6816e653e799feb05 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Fix ISI media device driver build error due to API renamed in bellow commit:
drivers/staging/media/imx/imx8-media-dev.c:196:22:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>