LF-3326-2 drm/imx: lcdifv3: fix several build errors during rebase
commit  ae9c25c0bc5d248617a277f5724aab6b7467e38c from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Due to the commit eca22edb37d2 (drm: Pass the full state to
connectors atomic functions), below build errors happened:

drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:227:18: error: initialization of ‘int (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘int (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  227 |  .atomic_check = lcdifv3_crtc_atomic_check,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:227:18: note: (near initialization for ‘lcdifv3_helper_funcs.atomic_check’)
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:228:18: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  228 |  .atomic_begin = lcdifv3_crtc_atomic_begin,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:228:18: note: (near initialization for ‘lcdifv3_helper_funcs.atomic_begin’)
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:229:18: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  229 |  .atomic_flush = lcdifv3_crtc_atomic_flush,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:229:18: note: (near initialization for ‘lcdifv3_helper_funcs.atomic_flush’)
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:230:19: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  230 |  .atomic_enable = lcdifv3_crtc_atomic_enable,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:230:19: note: (near initialization for ‘lcdifv3_helper_funcs.atomic_enable’)
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:231:20: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  231 |  .atomic_disable = lcdifv3_crtc_atomic_disable,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/imx/lcdifv3/lcdifv3-crtc.c:231:20: note: (near initialization for ‘lcdifv3_helper_funcs.atomic_disable’)

Signed-off-by: Fancy Fang <chen.fang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>