arm64: vpu: hantro: fix missing vmalloc.h include
commit  27ea8d7e4393808b81319253093014e93ead2cbb from
https://github.com/nxp-imx/linux-imx lf-6.12.y

drivers/mxc/hantro_v4l2/vsi-v4l2-priv.h:478:33: error: implicit declaration of function ‘vmalloc’; did you mean ‘kvmalloc’? [-Werror=implicit-function-declaration]
  478 |         struct cropinfo *crop = vmalloc(sizeof(struct cropinfo));
      |                                 ^~~~~~~
      |                                 kvmalloc

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Reviewed-by: Zhou Peng <eagle.zhou@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>