LF-9958-2 media: Samsung CSI2: fix build error due to API change
commit  6739d25ec86e5512d5d2a075ef10e6fb5afd2232 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Fix following build error.

drivers/staging/media/imx/imx8-mipi-csi2-sam.c:428:37: error: field 'asd' has incomplete type
  428 |         struct v4l2_async_subdev    asd;
      |                                     ^~~

caused by
commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection")

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>