net: fec_uio: fix build issues due to of_device.h and of_platform.h change
commit  39a36ab19b18e12069543d35aa4bc69487fc3eb3 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Cope with upstream change:
commit d57d584ef69d ("of: Stop circularly including of_device.h and of_platform.h")

e.g.
drivers/gpu/drm/panel/panel-raydium-rm67191.c:576:44: error: implicit declaration of function ‘of_match_device’; did you mean ‘i2c_of_match_device’? [-Werror=implicit-function-declaration]
  576 |         const struct of_device_id *of_id = of_match_device(rad_of_match, dev);
      |                                            ^~~~~~~~~~~~~~~
      |                                            i2c_of_match_device

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>