MA-23227 drm/imx: Fix build error for imx95-dpu-drm and imx-dcnano-drm module
commit  28a4bccd9c280a47483f8926bb5edd1e68f79d04 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

After modularizing the imx95-dpu-drm and imx-dcnano-drm, a build
error is encountered.

erro log:
ERROR: modpost: "drm_bridge_connector_init" [drivers/gpu/drm/imx/dpu95/imx95-dpu-drm.ko] undefined!
ERROR: modpost: "drm_bridge_connector_init" [drivers/gpu/drm/imx/dcnano/imx-dcnano-drm.ko] undefined!

The missing symbol drm_bridge_connector_init is provided by the
DRM_BRIDGE_CONNECTOR component, which is not explicitly selected by
the Kconfig for these drivers. Similarly, DRM_DISPLAY_HELPER is also
required as a dependency to properly initialize the DRM bridge
connectors.

Change-Id: I8d262320152bd19f754c193252e4a78f1ecd141c
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
Reviewed-by: Liu Ying <victor.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>