net: sdk_dpaa: fix build break
commit  ca2334b865607d37d5e07c77c2a11b1858dd5427 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

API changed since:
commit 00d066a4d4ed ("netdev_features: convert NETIF_F_LLTX to dev->lltx")

drivers/net/ethernet/freescale/sdk_dpaa/dpaa_eth.c: In function ‘dpa_private_netdev_init’:
drivers/net/ethernet/freescale/sdk_dpaa/dpaa_eth.c:774:50:
error: ‘NETIF_F_LLTX’ undeclared (first use in this function); did you mean ‘NETIF_F_LRO’?
  774 |                                 NETIF_F_RXCSUM | NETIF_F_LLTX;
      |                                                  ^~~~~~~~~~~~
      |                                                  NETIF_F_LRO

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>