LF-5447-2 [#imx-2829] Fix __GFP_ATOMIC API change in new kernel
commit  2c55f53fd814a946b948720831eb58d59b479239 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

GFP API changed since: 88c4e4bbb261 ("mm: discard __GFP_ATOMIC")

Use GFP_ATOMIC to replace __GFP_HIGH | __GFP_ATOMIC as generic fix

    ../drivers/mxc/gpu-viv/hal/os/linux/kernel/allocator/default/gc_hal_kernel_allocator_gfp.c: In function ‘_GFPAlloc’:
    ../drivers/mxc/gpu-viv/hal/os/linux/kernel/allocator/default/gc_hal_kernel_allocator_gfp.c:478:35: error: ‘__GFP_ATOMIC’ undeclared (first use in this function); did you mean ‘GFP_ATOMIC’?
      478 |     u32 normal_gfp = __GFP_HIGH | __GFP_ATOMIC | __GFP_NORETRY | gcdNOWARN;
          |                                   ^~~~~~~~~~~~
          |                                   GFP_ATOMIC

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>