MA-22385 neutron: Fix variable initialization causing build error
commit  8559699619d331efe3d3381b6e5f9fcaa5710626 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

error log:
drivers/staging/neutron/neutron_inference.c:348:3: error: expected expression
struct neutron_uapi_result_status uapi;

Change-Id: I8e33bd706f65660532e3ec650315dff369bcf055
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>