LF-1197-2 gpu: drm: imx: ipuv3: remove drmP.h
commit  34ce236c9c4b027836cb021035421d0d7ceef074 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

API changes:
4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

drivers/gpu/drm/imx/ipuv3/ipuv3-kms.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>