MGS-7841 [#imx-3332] make platform_driver::remove() return void in 6.10 kernel
commit  d9e655c74d8c513807585b4a7b9478b3e5b7dff5 from
https://github.com/nxp-imx/linux-imx lf-6.12.y

Update the .remove callback according to the kernel upstream:
0edb555a65d1 ("platform: Make platform_driver::remove() return void")

drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_driver.c:1319:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1319 |     .remove     = viv_dev_remove,
      |                   ^~~~~~~~~~~~~~
drivers/mxc/gpu-viv/hal/os/linux/kernel/platform/freescale/gc_hal_kernel_platform_imx.c:883:15: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  883 |     .remove = mxc_gpu_sub_remove,
      |               ^~~~~~~~~~~~~~~~~~
Signed-off-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>